from __future__ import annotations

import sqlite3

from app.services.workflow import generate_portal_token, refresh_job_readiness, refresh_job_recommendation


def seed_database(conn: sqlite3.Connection) -> None:
    installers = [
        ("Carlos Martinez", "carlos@example.com", "+1 214 555 0101", "Dallas", "TX", "TX, OK, LA, AR, NM", "toyota lp, forklifts, displays, industrial vehicles, standard installs, fast installs, warehouse fleets", 4),
        ("Ethan Brooks", "ethan@example.com", "+1 512 555 0106", "Austin", "TX", "TX, OK, NM, LA", "advanced diagnostics, hangcha, yale, hyster, mixed fleets, industrial vehicles, troubleshooting, team lead", 5),
        ("Mia Chen", "mia@example.com", "+1 469 555 0107", "Dallas", "TX", "TX", "basic installs, toyota lp, display mounts, support technician, warehouse fleets", 2),
        ("Ana Rivera", "ana@example.com", "+1 305 555 0102", "Miami", "FL", "FL, GA, AL, SC", "electric forklifts, crown, warehouse fleets, cable routing", 4),
        ("Mike Johnson", "mike@example.com", "+1 312 555 0103", "Chicago", "IL", "IL, IN, WI, MI, IA, MO", "diesel trucks, ford, isuzu, j1939, heavy duty", 4),
        ("Sofia Lopez", "sofia@example.com", "+1 404 555 0104", "Atlanta", "GA", "GA, TN, NC, SC, AL, FL", "toyota lp, hyster, propane, displays, mounts, forklifts", 4),
        ("James Wilson", "james@example.com", "+1 909 555 0105", "Riverside", "CA", "CA, NV, AZ, OR", "mixed fleets, telematics, basic installs, troubleshooting, mid level installer", 3),
        ("Priya Shah", "priya@example.com", "+1 951 555 0108", "Riverside", "CA", "CA, NV, AZ, OR, WA", "jungheinrich, relays, advanced electric forklifts, warehouse automation, complex diagnostics, team lead", 5),
    ]
    conn.executemany(
        """
        INSERT INTO installers
        (name, email, phone, home_city, home_state, coverage_states, skill_tags, max_complexity)
        VALUES (?, ?, ?, ?, ?, ?, ?, ?)
        """,
        installers,
    )

    vehicles = [
        ("Toyota", "LP", "LP", 1, 45, "toyota lp, propane, forklifts, display mounts, standard install, low difficulty", "Toyota LP is currently one of the easiest standard installs. Most jobs take about 30 to 60 minutes depending on installer speed and site readiness."),
        ("Jungheinrich", "EFG Series", "Electric", 5, 150, "jungheinrich, electric forklifts, relays, advanced diagnostics, high difficulty", "High-difficulty installation. Prepare relays and additional components before dispatch. Typical range is 90 to 180 minutes per unit."),
        ("Hangcha", "CPYD Series", "LP", 3, 90, "hangcha, lp, forklift, medium difficulty, mixed fleet", "Medium-difficulty forklift installation. Confirm mounting location, power source, and cable routing before starting."),
        ("Yale", "GP Series", "LP", 3, 90, "yale, lp, forklift, medium difficulty, mixed fleet", "Medium-difficulty forklift installation. Validate safe routing and protect wiring from heat and vibration."),
        ("Hyster", "H50FT", "LP", 4, 180, "hyster, propane, forklifts, ignition source, complex diagnostics", "For Hyster LP units, confirm power source and safe cable routing away from heat."),
        ("Crown", "FC Series", "Electric", 3, 140, "crown, electric forklifts, warehouse, cable routing", "Validate the power point and protect cabling around the battery compartment."),
        ("Ford", "F-650", "Diesel", 4, 170, "ford, diesel trucks, heavy duty, j1939", "May require J1939 network validation and a durable hardware mounting location."),
        ("Isuzu", "NPR", "Diesel", 3, 150, "isuzu, diesel trucks, medium duty", "Confirm panel access and harness protection before routing cables."),
    ]
    conn.executemany(
        """
        INSERT INTO vehicles
        (make, model, fuel_type, complexity, estimated_minutes, skill_tags, notes)
        VALUES (?, ?, ?, ?, ?, ?, ?)
        """,
        vehicles,
    )

    rules = [
        ("Toyota LP - longer display mounting screws", "toyota lp, toyota propane, display mount, screen mount, longer screws, easy install, standard install", "Toyota", "LP", "LP", 0, "drill, Phillips bits, metric sockets, multimeter, trim tool", "longer display mounting screws, zip ties, cable protectors, spare connectors", "Before departure: confirm Toyota LP model; pack longer display mounting screws; review display location; bring zip ties and cable protection.", "Toyota LP is a low-difficulty install, but many units still benefit from longer screws for the display mount. Bring them to avoid delays."),
        ("Jungheinrich electric units - prepare relays before dispatch", "jungheinrich, electric forklift, relays, advanced electric, high difficulty, additional components", "Jungheinrich", "EFG Series", "Electric", 0, "multimeter, relay prep kit, crimper, diagnostic laptop, insulated tools", "pre-prepared relays, additional connectors, spare fuses, cable protection, industrial tape", "Prepare relays before leaving; validate access to the electrical compartment; confirm power source and mounting location with the customer.", "High-difficulty job. Avoid dispatching a low-level installer alone. Missing relays or components can cause a failed visit."),
        ("Hangcha and Yale mixed fleet - medium difficulty checks", "hangcha, yale, mixed fleet, medium difficulty, lp forklift", "", "", "LP", 0, "multimeter, metric sockets, drill, flashlight, trim tool", "zip ties, cable protectors, spare connectors, fuses, industrial tape", "Confirm mounting location, safe cable routing, ignition source, and before/after photos for each unit.", "Medium-difficulty mixed fleet work benefits from one experienced lead and one support technician when scheduled with nearby jobs."),
        ("LP vehicles - safety and ignition source check", "lp, propane, gas, forklift", "", "", "LP", 0, "multimeter, heat protection, high-temperature tape, flashlight", "spare fuses, corrugated loom, heat-resistant zip ties", "Route wiring away from hot surfaces; validate a safe power source; document before and after photos.", "LP vehicles can have heat and vibration zones. Avoid cable routing near exhaust or regulator areas."),
        ("Heavy diesel trucks - validate J1939", "diesel, heavy duty, j1939, ford f-650, truck", "", "", "Diesel", 1, "multimeter, J1939 adapters, diagnostic laptop, crimper", "extra J1939 connectors, fuses, automotive tape, corrugated loom", "Validate J1939 network, ground, constant power, and ignition power. Take a photo of the connection point.", "The main risk is using the wrong connection point or having limited access to the harness."),
        ("Electric forklifts - protect battery-area wiring", "electric, crown, forklift, warehouse, battery compartment", "", "", "Electric", 0, "multimeter, trim tool, cable protection, flashlight", "corrugated loom, zip ties, insulated connectors, industrial electrical tape", "Confirm voltage and route wiring away from the battery compartment when applicable. Protect all wiring from abrasion.", "There is abrasion or acid/corrosion exposure risk near industrial batteries."),
    ]
    conn.executemany(
        """
        INSERT INTO knowledge_rules
        (title, triggers, vehicle_make, vehicle_model, fuel_type, complexity_adjustment, required_tools,
         required_materials, checklist, risk_notes)
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        """,
        rules,
    )

    jobs = [
        {
            "customer_name": "Lone Star Distribution",
            "customer_type": "Dealer",
            "customer_contact_name": "Megan Adams",
            "customer_contact_email": "megan.adams@example.com",
            "customer_contact_phone": "+1 817 555 0200",
            "dealer_name": "DFW Lift Trucks",
            "dealer_contact_name": "Tom Walker",
            "dealer_contact_email": "tom.walker@example.com",
            "dealer_contact_phone": "+1 817 555 0220",
            "sales_rep_name": "Internal Sales Rep",
            "sales_rep_email": "sales@example.com",
            "po_number": "PO-TX-1001",
            "hubspot_deal_id": "HS-90001",
            "installation_required": 1,
            "order_ready": 1,
            "shipment_carrier": "UPS",
            "shipment_tracking_number": "1Z999TX1001",
            "site_address": "1200 Industrial Blvd",
            "site_city": "Dallas",
            "site_state": "TX",
            "site_zip": "75207",
            "site_contact_name": "Warehouse Supervisor",
            "site_contact_email": "warehouse@example.com",
            "site_contact_phone": "+1 214 555 0333",
            "site_access_hours": "Mon-Fri 8:00 AM - 4:00 PM",
            "site_access_notes": "Check in at shipping office. PPE required.",
            "requested_date": "2026-05-12",
            "scheduled_start": "2026-05-12 08:00",
            "scheduled_end": "2026-05-12 15:30",
            "vehicle_make": "Toyota",
            "vehicle_model": "LP",
            "fuel_type": "LP",
            "vehicle_voltage": "12V",
            "vehicle_asset_ids": "TX-TY-001 to TX-TY-010",
            "installation_type": "Telematics + display",
            "quantity": 10,
            "assigned_installer_id": 1,
            "status": "confirmed",
            "coordinator_approved_by": "Operations Coordinator",
            "coordinator_approved_at": "2026-05-08 09:00",
            "notes": "Applied planning scenario: Work Order 1 in Texas. Toyota LP is low difficulty and can be consolidated with nearby Texas work.",
        },
        {
            "customer_name": "Lone Star Distribution",
            "customer_type": "Dealer",
            "customer_contact_name": "Megan Adams",
            "customer_contact_email": "megan.adams@example.com",
            "customer_contact_phone": "+1 817 555 0200",
            "dealer_name": "DFW Lift Trucks",
            "dealer_contact_name": "Tom Walker",
            "dealer_contact_email": "tom.walker@example.com",
            "dealer_contact_phone": "+1 817 555 0220",
            "sales_rep_name": "Internal Sales Rep",
            "sales_rep_email": "sales@example.com",
            "po_number": "PO-TX-1003-A",
            "hubspot_deal_id": "HS-90003",
            "installation_required": 1,
            "order_ready": 1,
            "shipment_carrier": "FedEx",
            "shipment_tracking_number": "7777TX1003A",
            "site_address": "700 Railhead Rd",
            "site_city": "Fort Worth",
            "site_state": "TX",
            "site_zip": "76106",
            "site_contact_name": "Fleet Lead",
            "site_contact_email": "fleetlead@example.com",
            "site_contact_phone": "+1 817 555 0444",
            "site_access_hours": "Mon-Fri 8:00 AM - 5:00 PM",
            "site_access_notes": "Ask for the fleet office.",
            "requested_date": "2026-05-13",
            "scheduled_start": "2026-05-13 09:00",
            "scheduled_end": "2026-05-13 10:30",
            "vehicle_make": "Hangcha",
            "vehicle_model": "CPYD Series",
            "fuel_type": "LP",
            "vehicle_voltage": "12V",
            "vehicle_asset_ids": "HC-FTW-017",
            "installation_type": "Telematics + display",
            "quantity": 1,
            "assigned_installer_id": 3,
            "status": "confirmed",
            "coordinator_approved_by": "Operations Coordinator",
            "coordinator_approved_at": "2026-05-08 09:05",
            "notes": "Applied planning scenario: Work Order 3 vehicle 1. Route planner should consider consolidation with Dallas Toyota LP work.",
        },
        {
            "customer_name": "Lone Star Distribution",
            "customer_type": "Dealer",
            "customer_contact_name": "Megan Adams",
            "customer_contact_email": "megan.adams@example.com",
            "customer_contact_phone": "+1 817 555 0200",
            "dealer_name": "DFW Lift Trucks",
            "dealer_contact_name": "Tom Walker",
            "dealer_contact_email": "tom.walker@example.com",
            "dealer_contact_phone": "+1 817 555 0220",
            "sales_rep_name": "Internal Sales Rep",
            "sales_rep_email": "sales@example.com",
            "po_number": "PO-TX-1003-B",
            "hubspot_deal_id": "HS-90003",
            "installation_required": 1,
            "order_ready": 1,
            "shipment_carrier": "FedEx",
            "shipment_tracking_number": "7777TX1003B",
            "site_address": "710 Railhead Rd",
            "site_city": "Arlington",
            "site_state": "TX",
            "site_zip": "76011",
            "site_contact_name": "Fleet Lead",
            "site_contact_email": "fleetlead@example.com",
            "site_contact_phone": "+1 817 555 0444",
            "site_access_hours": "Mon-Fri 8:00 AM - 5:00 PM",
            "site_access_notes": "Gate code required.",
            "requested_date": "2026-05-13",
            "scheduled_start": "2026-05-13 11:00",
            "scheduled_end": "2026-05-13 12:30",
            "vehicle_make": "Yale",
            "vehicle_model": "GP Series",
            "fuel_type": "LP",
            "vehicle_voltage": "12V",
            "vehicle_asset_ids": "YL-ARL-009",
            "installation_type": "Telematics + display",
            "quantity": 1,
            "assigned_installer_id": 2,
            "status": "confirmed",
            "coordinator_approved_by": "Operations Coordinator",
            "coordinator_approved_at": "2026-05-08 09:05",
            "notes": "Applied planning scenario: Work Order 3 vehicle 2. Nearby to the Dallas/Fort Worth Toyota LP work.",
        },
        {
            "customer_name": "Pacific Cold Storage",
            "customer_type": "Customer",
            "customer_contact_name": "Olivia Grant",
            "customer_contact_email": "olivia.grant@example.com",
            "customer_contact_phone": "+1 951 555 0202",
            "dealer_name": "",
            "dealer_contact_name": "",
            "dealer_contact_email": "",
            "dealer_contact_phone": "",
            "sales_rep_name": "West Sales Rep",
            "sales_rep_email": "west.sales@example.com",
            "po_number": "PO-CA-2002",
            "hubspot_deal_id": "HS-91002",
            "installation_required": 1,
            "order_ready": 1,
            "shipment_carrier": "UPS",
            "shipment_tracking_number": "1Z999CA2002",
            "site_address": "4100 Warehouse Ave",
            "site_city": "Riverside",
            "site_state": "CA",
            "site_zip": "92501",
            "site_contact_name": "Maintenance Manager",
            "site_contact_email": "maintenance@example.com",
            "site_contact_phone": "+1 951 555 0444",
            "site_access_hours": "Tue-Thu 7:00 AM - 5:00 PM",
            "site_access_notes": "Electric fleet; confirm lockout/tagout before work.",
            "requested_date": "2026-05-12",
            "scheduled_start": "2026-05-12 08:00",
            "scheduled_end": "2026-05-12 18:00",
            "vehicle_make": "Jungheinrich",
            "vehicle_model": "EFG Series",
            "fuel_type": "Electric",
            "vehicle_voltage": "48V",
            "vehicle_asset_ids": "JH-RIV-001 to JH-RIV-004",
            "installation_type": "Telematics + relays",
            "quantity": 4,
            "assigned_installer_id": 8,
            "status": "confirmed",
            "coordinator_approved_by": "Operations Coordinator",
            "coordinator_approved_at": "2026-05-08 09:10",
            "notes": "Applied planning scenario: Work Order 2 in California. High difficulty; requires relays and advanced support.",
        },
        {
            "customer_name": "Blue Ridge Equipment",
            "customer_type": "Dealer",
            "customer_contact_name": "Nina Patel",
            "customer_contact_email": "nina.patel@example.com",
            "customer_contact_phone": "+1 704 555 0111",
            "dealer_name": "Blue Ridge Equipment",
            "dealer_contact_name": "Nina Patel",
            "dealer_contact_email": "nina.patel@example.com",
            "dealer_contact_phone": "+1 704 555 0111",
            "sales_rep_name": "East Sales Rep",
            "sales_rep_email": "east.sales@example.com",
            "po_number": "PO-NC-3001",
            "hubspot_deal_id": "HS-92001",
            "installation_required": 1,
            "order_ready": 1,
            "shipment_carrier": "FedEx",
            "shipment_tracking_number": "4499NC3001",
            "site_address": "1800 Logistics Pkwy",
            "site_city": "Charlotte",
            "site_state": "NC",
            "site_zip": "28208",
            "site_contact_name": "Receiving Manager",
            "site_contact_email": "receiving@example.com",
            "site_contact_phone": "+1 704 555 0666",
            "site_access_hours": "Mon-Fri 8:30 AM - 4:30 PM",
            "site_access_notes": "No weekend access.",
            "requested_date": "2026-05-19",
            "vehicle_make": "Crown",
            "vehicle_model": "FC Series",
            "fuel_type": "Electric",
            "vehicle_voltage": "36V",
            "vehicle_asset_ids": "CR-CLT-021, CR-CLT-022",
            "installation_type": "Telematics + display",
            "quantity": 2,
            "assigned_installer_id": None,
            "status": "pending_approval",
            "coordinator_approved_by": "",
            "coordinator_approved_at": None,
            "notes": "Complete required information is available. This should stay in Pending Coordinator Approval until a coordinator confirms the AI recommendation.",
        },
        {
            "customer_name": "Midwest Food Logistics",
            "customer_type": "Customer",
            "customer_contact_name": "Sam Rivera",
            "customer_contact_email": "sam.rivera@example.com",
            "customer_contact_phone": "+1 312 555 0188",
            "dealer_name": "",
            "dealer_contact_name": "",
            "dealer_contact_email": "",
            "dealer_contact_phone": "",
            "sales_rep_name": "Central Sales Rep",
            "sales_rep_email": "central.sales@example.com",
            "po_number": "PO-IL-4001",
            "hubspot_deal_id": "HS-93001",
            "installation_required": 1,
            "order_ready": 0,
            "shipment_carrier": "",
            "shipment_tracking_number": "",
            "site_address": "",
            "site_city": "Chicago",
            "site_state": "IL",
            "site_zip": "",
            "site_contact_name": "",
            "site_contact_email": "",
            "site_contact_phone": "",
            "site_access_hours": "",
            "site_access_notes": "Customer must confirm exact dock address and vehicle list.",
            "requested_date": "2026-05-22",
            "vehicle_make": "Toyota",
            "vehicle_model": "LP",
            "fuel_type": "LP",
            "vehicle_voltage": "",
            "vehicle_asset_ids": "",
            "installation_type": "Telematics + display",
            "quantity": 6,
            "assigned_installer_id": None,
            "status": "waiting_required_info",
            "coordinator_approved_by": "",
            "coordinator_approved_at": None,
            "notes": "Example blocked job. The system should not allow technician confirmation until site address, contact, voltage, asset IDs, and tracking are provided.",
        },
    ]

    for job in jobs:
        fields = list(job.keys()) + ["portal_token"]
        values = [job.get(key) for key in job.keys()] + [generate_portal_token()]
        placeholders = ", ".join("?" for _ in fields)
        conn.execute(
            f"INSERT INTO jobs ({', '.join(fields)}) VALUES ({placeholders})",
            values,
        )
    conn.commit()

    job_ids = [row[0] for row in conn.execute("SELECT id FROM jobs").fetchall()]
    for job_id in job_ids:
        refresh_job_recommendation(conn, job_id)
        refresh_job_readiness(conn, job_id)
    conn.commit()
